spring.datasource:
  platform: h2
  url: jdbc:h2:./camunda-db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
  username: sa
  password: sa
  driverClassName: org.h2.Driver
spring:
  h2.console.enabled: true
  servlet.multipart.enabled: false
camunda.bpm:
  filter:
    create: All Tasks
  job-execution:
    enabled: true
    deployment-aware: true
  admin-user:
    id: demo
    password: demo
    firstName: Demo
    lastName: Demo
server.port: 8080
vaadin:
  urlMapping: /client/*